/*
Simon Says Game — Logic Overview & Rules

How the Game Works:
- The game starts when the player presses any key.
- At the start of each level, the game flashes one random colored box (from 4 total boxes).
- The sequence of flashes grows with each level — for example:
  Level 1 → 1 flash
  Level 2 → previous sequence + 1 new flash
  Level 3 → previous sequence + 1 new flash, and so on.

Player's Goal:
- The player must remember and click the boxes in the exact same order as shown by the game.
- After every correct round, the level increases, and the sequence length grows by one.

Game Logic:
- `gameSeq[]`: Stores the correct flashing order generated by the game.
- `userSeq[]`: Stores the player's clicks (their attempt to repeat the pattern).
- `nextLevel()`: Generates the next random flash and updates the level.
- `flashBox()`: Adds a temporary CSS class to make a box “flash”.
- `checkAnswer()`: Compares the player's current input with the game sequence:
    - If correct so far → waits until the player finishes the sequence.
    - If full sequence is correct → moves to the next level.
    - If any mismatch → triggers "Game Over" and resets the game.
- `resetGame()`: Resets all values and allows restart after any key press.

Rules:
1. Press any key to start.
2. Watch the flashing sequence carefully.
3. Click the boxes in the same order.
4. Each round adds one more flash.
5. One wrong click ends the game.
*/

// Arrays to hold the game-generated sequence and the user's input sequence
let gameSeq = [];
let userSeq = [];

// Variables to track game state and current level
let start = false;
let level = 1;

// Selecting the heading element to display level or messages
let head2 = document.querySelector('h2');

// Event listener to start the game when the player presses any key
document.addEventListener('keypress', function() {
    // This ensures the game only starts once, not every key press
    if (!start) {
        head2.innerText = `Level ${level}`; // Display the current level
        start = true; // Mark that the game has started
        nextLevel();  // Begin the first level
    }
});

function nextLevel() {
    // Clear user's previous sequence before starting the new round
    userSeq = [];

    // Generate a random number between 1–4 (each number represents a box)
    let randomNum = Math.floor(Math.random() * 4) + 1;

    // Select the corresponding div box using the random number
    let randomDiv = document.querySelector(`.btn-${randomNum}`);

    // Flash the randomly selected box to show it to the player
    flashBox(randomDiv);

    // Add this random number to the game sequence
    gameSeq.push(randomNum);

    console.log("Game sequence:", gameSeq); // For debugging / tracking
}

function flashBox(box) {
    // Adds the 'flash' class to visually highlight the box
    box.classList.add("flash");

    // Removes the flash effect after a short delay (300ms)
    setTimeout(() => {
        box.classList.remove("flash");
    }, 300);
}

// Loop through all 4 boxes and attach click event listeners
for (let i = 1; i <= 4; i++) {
    let btn = document.querySelector(`.btn-${i}`);

    btn.addEventListener('click', function() {
        // When clicked, add that box's number to the user's sequence
        userSeq.push(i);

        // Flash the clicked button for feedback
        flashBox(btn);

        // Check if the user's input so far matches the game sequence
        checkAnswer(userSeq.length - 1);
    });
}

function checkAnswer(currentIndex) {
    // Compare user's latest click with corresponding game sequence value
    if (userSeq[currentIndex] === gameSeq[currentIndex]) {

        // If user completed the entire sequence correctly for this level
        if (userSeq.length === gameSeq.length) {
            level++; // Increase level
            head2.innerText = `Level ${level}`; // Update display

            // Start next level after a short delay
            setTimeout(nextLevel, 800);
        }

    } else {
        // If mismatch found → Game Over
        head2.innerText = "Game Over! Press any key to Restart.";
        console.log("GAME OVER!");

        // Reset all progress and variables for restart
        resetGame();
    }
}

function resetGame() {
    // Reset all essential variables to initial state
    start = false;
    level = 1;
    gameSeq = [];
    userSeq = [];
}
